server:
  port: 8082


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/microservice
    username: postgres
    password: Ashish@2003
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true